// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Chat-Backend")]
[assembly: AssemblyDescriptionAttribute("A backend project for my chat fun")]
[assembly: GuidAttribute("EE5621DB-B86B-44eb-987F-9C94BCC98441")]
[assembly: AssemblyProductAttribute("Chat")]
[assembly: AssemblyVersionAttribute("0.2")]
[assembly: AssemblyFileVersionAttribute("0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Chat-Backend";
        internal const System.String AssemblyDescription = "A backend project for my chat fun";
        internal const System.String Guid = "EE5621DB-B86B-44eb-987F-9C94BCC98441";
        internal const System.String AssemblyProduct = "Chat";
        internal const System.String AssemblyVersion = "0.2";
        internal const System.String AssemblyFileVersion = "0.2";
    }
}
